maths/emath/urls.py
from django.urls import path
from . import views
app_name='emath'
urlpatterns=[
    path('',views.index,name='index'),
    path('root',views.root,name='root'),
    path('quadratic',views.quadratic,name='quadratic'),
    path('cubic',views.cubic,name='cubic')
]

maths/maths/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('emath/',include('emath.urls'))
]

maths/emath/models.py
from django.db import models

# Create your models here.

maths/emath/views.py
from django.shortcuts import render
import numpy as n
from django import forms
def index(request):
    return render(request,'index.html')
def root(request):
    return render(request,'root.html')
def quadratic(request):
      class quadform(forms.Form):
           x2=forms.IntegerField(label='Co-eff of  X^2 ')
           print(end='/n')
           x=forms.IntegerField(label='Co-eff of  X ')
           const=forms.IntegerField(label='Constant term')
      if request.method=='POST':
            form=quadform(request.POST)
            if form.is_valid():
                 x=form.cleaned_data['x2']
                 y=form.cleaned_data['x']
                 z=form.cleaned_data['const']
                 res=n.roots([x,y,z])
                 return render(request,'result2.html',{'res':res})

      return render(request,'quad.html',{'form':quadform()})
def cubic(request):
      class cubicform(forms.Form):
             x3=forms.IntegerField(label='Co-eff of X^3')
             x2=forms.IntegerField(label='Co-eff of X^2')
             x=forms.IntegerField(label='Co-eff of X')
             Const=forms.IntegerField(label='Constant term')
      if request.method=="POST":
            form=cubicform(request.POST)
            if form.is_valid():
                 a=form.cleaned_data['x3']
                 b=form.cleaned_data['x2']
                 c=form.cleaned_data['x']
                 d=form.cleaned_data['Const']
                 res=n.roots([a,b,c,d])
                 return render(request,'result3.html',{'res':res.real})
      return render(request,'cubic.html',{'form':cubicform()})
# Create your views here.

maths/emath/templates/cubic.html
<!DOCTYPE html>
<html>
   <head>
      <title>SOLVING CUBIC EQUATION</title>
   </head>
   <body style='background-color:aqua'>
         <marquee style='background-color:teal;height:1.5cm;font-size:50px'>DISCLAIMER :  ENTER THE CORRECT VALUES !!</marquee>
         
         <form style='padding:40px;width:max-width;font-size:26px ;font-weight:bold' action='{%url "emath:cubic" %}' method=POST>
            {%csrf_token%} 
              <br></br>
                {% for field in form  %}
    {{ field.errors }}
    <li style='font-size:30px'> {{ field.label_tag }} {{ field }} </li>
    <br>
    
  {% endfor %}
                
            <button> <input type='submit'></button>
         </form>
    </body>
</head>
       

maths/emath/templates/index.html
<!DOCTYPE html>
<html>
     <head>
           <title>Emath Index</title>
           <style>
                 body{
                     background-color:black
                 }
                 #roots{
                     background-color:orange;
                     border:solid black
                 }
                 button:hover{
                     background-color:gray
                 }
            </style>
     </head>
     <body>
            <marquee style='background-color:palegreen; font-size:50px;height:1.5cm;'>WELCOME TO EMATH !! :)</marquee>
            <a href='{% url "emath:root"%}'style='text-decoration:none;color:black' >
            <div id='roots'>
                   <p style='font-size:30px;text-align:center;font-size:60px'>ROOTS OF THE EQUATION</p>
                   <br>
                   
            </div>
            </a>
     </body>
</html>

maths/emath/templates/quad.html
<!DOCTYPE html>
<html>
   <head>
      <title>SOLVING QUADRATIC EQUATION</title>
   </head>
   <body style='background-color:skyblue'>
         <marquee style='background-color:pink;height:1.5cm;font-size:50px'>DISCLAIMER :  ENTER THE CORRECT VALUES !!</marquee>
         
         <form style='padding:90px;width:40cm;font-size:26px ;font-weight:bold' action='{%url "emath:quadratic" %}' method=POST>
            {%csrf_token%} 
              <br></br>
                {% for field in form  %}
    {{ field.errors }}
    <li style='font-size:30px'> {{ field.label_tag }} {{ field }} </li>
    <br>
    
  {% endfor %}
               
            <button> <input type='submit'></button>
         </form>
    </body>
</head>
       

maths/emath/templates/result2.html
<!DOCTYPE html>
</html>
     <head>
          <title> Result </title>
     </head>
     <body style='background-color:yellow'>
        <div style='padding=110px'>
               <p style='font-size:60px'> THE ROOTS ARE   </p>
               <ul>
                   {%for ress in res%}
                         <li style='font-size:30px'>{{ress}}</li>
                         <br>
                   {%endfor%}
                </ul>
        <a href='{%url "emath:quadratic"%}' style='text-decoration:none'><button>RETRY</button></a>
        </div>
    </body>
</html>

maths/emath/templates/result3.html
<!DOCTYPE html>
</html>
     <head>
          <title> Result </title>
     </head>
     <body style='background-color:yellow'>
        <div style='padding=110px'>
               <p style='font-size:60px'> THE ROOTS ARE   </p>
               <ul>
                   {%for ress in res%}
                         <li style='font-size:30px'>{{ress}}</li>
                         <br>
                   {%endfor%}
                </ul>
               <a href='{%url "emath:cubic"%}' style='text-decoration:none'><button>RETRY</button>
        </div>
    </body>
</html>

maths/emath/templates/root.html
<!DOCTYPE html>
<html>
    <head>
         <title> ROOTS OF THE EQUATION</title>
         <style>
               body{
                   background-color:black;
               }

         </style>
    </head>
    <body>
        <marquee style='background-color:palegreen;font-size:50px;height:1.5cm'>ROOT OF THE EQUATION</marquee>
        <br>
       <a href='{%url "emath:quadratic"%}' style='text-decoration:none ; color:black'>
        <div id='two'style='background-color:orange;width:25cm;padding:center'>
          <p style='font-size:30px;text-align:center;font-size:60px'>QUADRATIC EQUATION</p>
        </div>
       </a>
       <a href='{%url "emath:cubic"%}' style='text-decoration:none;color:black'>
           <div id='cubic' style='background-color:aqua;width:25cm;padding:center'>
               <p style='font-size:30px;text-align:center;font-size:60px'>CUBIC EQUATION</p>
           </div>
       </a>
    </body>
</html>
                 